# $ conda create --name <env> --file <this file>
name: prep
channels:
  - salilab
  - conda-forge
dependencies:
  - python=3.13
  - requests
  - openmm
  - pdbfixer
  - modeller
  - biopython
  - pytest
  - mdanalysis
  - openmmtools
  - rdkit
  - openff-toolkit
  - pip
  - ambertools
  - pip:
    - pdbe-mmcif-validator
