{% set name = "prepmd" %}
{% set version = "0.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - prepmd=prepmd.prep:entry_point
    - runmd=prepmd.run:entry_point
    - prep-license=prepmd.add_modeller_license:entry_point

requirements:
  host:
    - python >=3.13,<3.14
    - pip
    - flit-core >=3.4,<4

  run:
    - python >=3.13,<3.14
    - requests
    - openmm
    - pdbfixer
    - biopython
    - pdb2pqr
    - mdanalysis
    - rdkit
    - openmmforcefields
    - openff-toolkit

test:
  imports:
    - prepmd

  commands:
    - python -c "import prepmd; print(prepmd.__version__)"
    - prepmd --help
    - runmd --help

about:
  home: https://github.com/CCPBioSim/prepmd
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  license_url: https://github.com/CCPBioSim/prepmd/blob/main/LICENSE
  summary: Automatically prepare PDB and mmCIF structures for molecular dynamics simulations.
  description: >-
    prepmd is a Python utility for automatically preparing PDB and mmCIF
    structures for molecular dynamics simulations. It provides tools for
    preparing, repairing, and processing molecular structures using OpenMM,
    PDBFixer, Biopython, MDAnalysis, RDKit, PDB2PQR, OpenMMForceFields,
    and the OpenFF Toolkit.
  dev_url: https://github.com/CCPBioSim/prepmd
  doc_url: https://prepmd.readthedocs.io/en/latest/
  doc_source_url: https://github.com/CCPBioSim/prepmd/blob/main/README.md