package:
  name: prepmd
  version: 1.0

source:
  #git_url: https://www.github.com/ccpbiosim/prepmd.git
  path: ..

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - requests
    - openmm
    - pdbfixer
    - modeller
    - biopython
    - mdanalysis
    - openmmtools
    - rdkit
    - openff-toolkit
test:
  commands:
    - prep-license MODELIRANJE
  imports:
    - prepmd

about:
  summary: A utility to automatically prepare structures from the PDB for molecular dynamics simulation
  dev_url: https://github.com/CCPBioSim/prepmd
  license: GNU Affero General Public License v3.0
  license_file: LICENSE
